### ISSUE TITLE
Add Pierre Auriau

### ISSUE THREAD

**Issue by duchesnay** [neurospin/gaia#1]
**Personal information**
- First name: Pierre
- Last name: Auriau
- Title: PhD student

**Team**
- [ ] ARCHITECTURE
- [ ] BRAINOMICS
- [ ] GINKGO
- [X] SIGNATURE
- [ ] CATI
- [ ] Platform

**Position**
- [] PI
- [] Post Doc
- [X] Grad Student
- [ ] Engineer

**Personal site**
- Optionally, you can add a link to your personal website.

**Comment by duchesnay** [comment]
How to add years ?
How to add supervision (in desc field) ?

**Comment by AGrigis** [comment]
These fields have been added.
